apiVersion: v1
kind: Service
metadata:
  labels:
    app: skyhelp
  name: skyhelp
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.skyhelp.service.port }}
      protocol: TCP
      targetPort: {{ .Values.skyhelp.service.targetPort }}
  selector:
    app: skyhelp
  type: {{ .Values.skyhelp.service.type }}