apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hangar
  namespace: hangar
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: skyops.hangar.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: skyops
                port:
                  number: 7000
