# Default values for skyhelp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: hangar

imagePullPolicy: IfNotPresent

skyhelp:
  image: skyhelp:latest
  replicas: 1
  service:
    port: 7010
    targetPort: 8080
    type: ClusterIP
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"
