services:
  
  skyops:
    image: skyops:latest
    container_name: skyops
    build:
      context: .
      dockerfile: ./SkyOps/Dockerfile
    ports:
      - 9000:8080
      
  skyhelp:
    image: skyhelp:latest
    container_name: skyhelp
    build:
      context: .
      dockerfile: ./SkyHelp/Dockerfile
    ports:
      - 9010:8080
