apiVersion: v1
kind: Service
metadata:
  labels:
    app: skyops
  name: skyops
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.skyops.service.port }}
      protocol: TCP
      targetPort: {{ .Values.skyops.service.targetPort }}
  selector:
    app: skyops
  type: {{ .Values.skyops.service.type }}