name: "bookstore"

on:
  push:
    paths:
      - "golang/bookstore/**"
      - ".github/workflows/bookstore.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.5"
          cache: false

      - name: Go version
        run: go version

      - name: Run tests
        run: |-
          cd golang/bookstore
          go test ./... -json | tee go-test-results-bookstore.json

      - name: Upload Go test results
        uses: actions/upload-artifact@v5
        with:
          name: Go-results-bookstore
          path: golang/bookstore/go-test-results-bookstore.json
