name: "bookstore"

on:
  push:
    paths:
      - "golang/bookstore/**"
      - ".github/workflows/go-bookstore.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.5"
          cache: false

      - name: Go version
        run: go version

      - name: Install dependencies
        run: |-
            cd golang/bookstore
            make deps

      - name: Run tests
        run: |-
            cd golang/bookstore
            make test
