name: "bookstore2"

on:
  push:
    paths:
      - "golang/bookstore2/**"
      - ".github/workflows/go-bookstore2.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.5"
          cache: false

      - name: Go version
        run: go version

      - name: Install dependencies
        run: |-
          cd golang/bookstore2
          make deps

      - name: Run tests
        run: |-
          cd golang/bookstore2
          go test -v ./...
